### ISSUE TITLE
Allow fold to use a different type on the accumulator

### ISSUE THREAD

**Issue by sporto** [emmanueltouzery/prelude-ts#56]
`Vector.fold` and similar have a signature like:

```
fold(zero: T, fn: (v1: T, v2: T): T): T
```

Many times you want to fold into a different type
This is common in FP langs. e.g. https://package.elm-lang.org/packages/elm/core/latest/List#foldl

I'm missing an alternative function?

Consider changing this to something like, where the accumulator can be something different.

```
fold(zero: U, fn: (v1: T, v2: U): U): U
```

**Comment by emmanueltouzery** [comment]
I believe you're looking for foldLeft? See the foldable interface:
<http://emmanueltouzery.github.io/prelude.ts/latest/apidoc/interfaces/foldable.html>

**Comment by emmanueltouzery** [comment]
closing for now, I believe I answered. If that's not the case, please reopen.

**Comment by sporto** [comment]
Yes, it seems so, thanks
