### ISSUE TITLE
Tuple2 equality is broken

### ISSUE THREAD

**Issue by jorge-fernandes** [emmanueltouzery/prelude-ts#58]
`Tuple2.of(0, "").equals(Tuple2.of(0, ""))`  yields false

I'm on version 1.0.2

**Comment by emmanueltouzery** [comment]
well that is embarrassing. Good catch and I hope you didn't spend too much time tracking this one down... I fixed it now, and published a new version of the library on npm, 1.0.4! Thank you for reporting.
